; KinetiKey — Gesture-Combination Lock
; Board: STM32 B-L475E-IOT01A (disco_l475vg_iot01a)

[env:disco_l475vg_iot01a]
platform           = ststm32
board              = disco_l475vg_iot01a
framework          = mbed
monitor_speed      = 115200
upload_protocol    = stlink
debug_tool         = stlink
debug_speed        = 500
